---
apiVersion: v2
name: comic-utils
description: A set of utilities for managing large comic libraries in Komga
type: application
version: 1.0.1
appVersion: "v1.2"
sources:
  - https://github.com/allaboutduncan/comic-utils
dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
